analysis:
  chunk_size: 1000
  enable_ai_analysis: true
  enable_content_analysis: true
  max_content_length: 100000
  overlap_size: 200
app:
  debug: false
  host: 0.0.0.0
  name: AnalyDesign
  port: 8000
  version: 1.0.0
coder_agent:
  ai_provider: volcengine
  backend_template_path: templates/back_construct.md
  backend_test_framework: junit5
  code_generation:
    backend_framework: spring_boot
    backend_java_version: '8'
    backend_package_prefix: com
    backend_version: 2.7.x
    frontend_framework: vue2
  code_generation_model: ep-20250724094351-pnjf4
  frontend_template_path: templates/fronted_construct.md
  frontend_test_framework: jest
  git_config:
    commit_prefix:
      chore: 构建变更
      docs: 文档更新
      feat: 新功能
      fix: 修复问题
      refactor: 重构代码
      style: 代码格式
      test: 添加测试
    default_branch: main
    default_branch_pattern: D_{timestamp}_aigc
    default_remote_url: https://github.com/sharoA/testproject.git
  max_tokens: 4000
  project_root: /Users/renyu/Documents/create_project
  review_model: ep-20250724094351-pnjf4
  tasks_dir: tasks
  tech_stack_docs_dir: docs/tech-stack
  temperature: 0.7
  test_coverage_target: 0.8
  test_project_dir: test-project
directories:
  analysis_results: uploads/analysis_results
  cache: uploads/cache
  logs: logs
  temp: uploads/temp
  uploads: uploads
file_upload:
  allowed_extensions:
  - .txt
  - .md
  - .pdf
  - .docx
  - .doc
  - .pptx
  - .ppt
  max_size: 52428800
  temp_dir: uploads/temp
logging:
  backup_count: 7
  file: logs/app.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  max_size: 10485760
openai:
  api_key: ''
  base_url: https://api.openai.com/v1
  max_tokens: 4000
  model: gpt-3.5-turbo
  temperature: 0.7
redis:
  cache:
    default_ttl: 3600
    key_prefix: 'analydesign:'
  connection_pool:
    max_connections: 50
  db: 0
  decode_responses: true
  host: localhost
  password: ''
  port: 6379
  socket_connect_timeout: 30
  socket_keepalive: true
  socket_keepalive_options: {}
  socket_timeout: 30
validation:
  allowed_file_types:
  - text/plain
  - application/pdf
  - application/msword
  - application/vnd.openxmlformats-officedocument.wordprocessingml.document
  - text/markdown
  - application/json
  - text/html
  - application/xml
  max_content_length: 10485760
  max_file_size: 52428800
  min_content_length: 1
vector_database:
  dimension: 768
  faiss:
    index_file: uploads/cache/vector_index.faiss
    metadata_file: uploads/cache/vector_metadata.json
  type: weaviate
  weaviate:
    api_key: root-user-key
    default_collection:
      name: AnalyDesignDocuments
      vector_dimension: 768
      vectorizer: none
    grpc_port: 50051
    host: localhost
    port: 8080
    scheme: http
    timeout: 30
volcengine:
  api_key: 7fcb3541-9363-4bfa-90aa-19e9f691bc25
  endpoint: https://ark.cn-beijing.volces.com/api/v3
  max_tokens: 16000
  model: ep-20250605091804-wmw6w
  temperature: 0.7
